---

- name: update cache
  become: true
  apt:
    update_cache: yes

#- name: install bridge-utils
#  become: true
#  apt:
#    name: bridge-utils

#- name: install unzip
#  become: true
#  apt:
#    name: unzip

#- name: install openvswitch-switch
#  become: true
#  apt:
#    name: openvswitch-switch

#- name: install openvswitch-common
#  become: true
#  apt:
#    name: openvswitch-common

#- name: ensure docker repository key is installed
#  apt_key:
#    id: "{{ docker_apt_key_id }}"
#    keyserver: "{{ docker_apt_keyserver }}"
#    state: present
#
#- name: ensure docker registry is available
#  apt_repository:
#    repo: "{{ docker_apt_repo }}"
#    update_cache: yes
#    state: present
#
#- name: install docker-engine
#  apt:
#    name: docker-engine
#
#- name: add user {{ ansible_user }} to docker group
#  user:
#    name: "{{ ansible_user }}"
#    groups: docker
#    append: yes
#
#- name: restart docker service
#  service:
#    name: docker
#    state: restarted
#
#- name: get docker compose
#  get_url:
#    url: "{{ docker_compose_url }}"
#    dest: /usr/local/bin/docker-compose
#    mode: 0755
#
#- name: install python-pip
#  apt:
#    name: python-pip
#
#- name: install docker-py
#  pip:
#    name: docker-py
#
#- name: install python-yaml
#  apt:
#    name: python-yaml
#
#- name: install ipvsadm
#  apt:
#    name: ipvsadm
#
#- name: install fabric
#  apt:
#    name: fabric
#
#- name: install python-memcache
#  apt:
#    name: python-memcache
#
#- name: install python-psutil
#  apt:
#    name: python-psutil
#
#- name: install cpulimit
#  apt:
#    name: cpulimit
